old-dtb := $(dtb-y)
dtb-y :=
makefile-path := platform/t210/hawkeye/kernel-dts

dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-hawkeye-p2290-a00-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-hawkeye-p2290-a00-wifi-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-hawkeye-p2290-2302-a01-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-hawkeye-p2290-3302-a01-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-hawkeye-p2290-3303-a01-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-hawkeye-p2290-2303-a01-00-wifi.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-hawkeye-p2290-2306-a01-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-hawkeye-p2290-3306-a01-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-hawkeye-p2290-3303-a02-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-hawkeye-p2290-2303-a02-00-wifi.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-hawkeye-p2290-3306-a02-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-hawkeye-p2290-2306-a02-00-wifi.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-hawkeye-ffpb-e2295-a00-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-hawkeye-p2290-3324-a03-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-hawkeye-p2290-2324-a03-00-wifi.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-hawkeye-p2290-3326-a03-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-hawkeye-p2290-2326-a03-00-wifi.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-hawkeye-p2290-a00-00-base.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-hawkeye-p2290-2302-a01-00-base.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-hawkeye-p2290-2306-a01-00-base.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-hawkeye-p2290-3302-a01-00-base.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-hawkeye-p2290-3303-a01-00-base.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-hawkeye-p2290-3306-a01-00-base.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-hawkeye-p2290-3303-a02-00-base.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-hawkeye-p2290-3306-a02-00-base.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-hawkeye-p2290-3324-a03-00-base.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-hawkeye-p2290-3326-a03-00-base.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-hawkeye-p2290-3304-a03-00-base.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-hawkeye-p2290-3304-a03-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-hawkeye-p2290-2304-a03-00-wifi.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-hawkeye-p2290-3306-a03-00-base.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-hawkeye-p2290-3306-a03-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-hawkeye-p2290-2306-a03-00-wifi.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-hawkeye-p2290-3304-a04-00-base.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-hawkeye-p2290-3304-a04-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-hawkeye-p2290-3306-a04-00-base.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-hawkeye-p2290-3306-a04-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-hawkeye-p2290-3304-a04-00-wifi.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-hawkeye-p2290-3306-a04-00-wifi.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-hawkeye-p2290-2305-a05-00-wifi.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-hawkeye-p2290-2306-a05-00-wifi.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-hawkeye-p2290-2307-a05-00-wifi.dtb

ifneq ($(dtb-y),)
dtb-y := $(addprefix $(makefile-path)/,$(dtb-y))
endif

dtb-y += $(old-dtb)
