old-dtb := $(dtb-y)
dtb-y :=
makefile-path := platform/t210/foster/kernel-dts

dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-darcy-p2894-0000-a00-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-darcy-p2894-0050-a04-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-darcy-p2894-0050-a08-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-darcy-p2894-0052-a08-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-foster-e-p2530-0930-e00-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-foster-e-p2530-0930-e01-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-foster-e-p2530-0930-e02-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-foster-e-hdd-p2530-0932-e00-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-foster-e-hdd-p2530-0932-e01-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-foster-e-hdd-p2530-0932-e02-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-foster-e-hdd-cpc-p2530-0933-e03-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-foster-e-hdd-rpmb-p2530-0931-e02-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-foster-e-e2581-0930-a00-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-foster-e-e2581-0930-a01-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-loki-e-p2530-0031-e00-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-loki-e-p2530-0031-e01-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-loki-e-p2530-0031-e02-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-loki-e-p2530-0031-e03-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-loki-e-p2530-0030-e00-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-loki-e-p2530-0030-e01-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-loki-e-p2530-0030-e02-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-loki-e-p2530-0030-e03-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-loki-e-p2530-0131-e00-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-loki-e-p2530-0131-e01-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-loki-e-p2530-0131-e02-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-loki-e-e2581-0030-a00-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-loki-e-e2581-0030-a01-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-loki-e-e2581-0031-a00-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-loki-e-e2581-0031-a01-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-loki-e-e2581-0131-a00-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-loki-e-e2581-0131-a01-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_210_SOC) += tegra210-loki-vcm30t210.dtb

ifneq ($(dtb-y),)
dtb-y := $(addprefix $(makefile-path)/,$(dtb-y))
endif

dtb-y += $(old-dtb)
